#include "PhotonWeapon.h"

#include "Components/StaticMeshComponent.h"
#include "Components/PrimitiveComponent.h"
#include "Engine/StaticMesh.h"
#include "Net/UnrealNetwork.h"
#include "PhotonCore.h"
#include "PhotonPlayer.h"

// ---------------------------------------------------------------------------------------------
// APhotonWeapon
// ---------------------------------------------------------------------------------------------

APhotonWeapon::APhotonWeapon()
{
	PrimaryActorTick.bCanEverTick = false;
	bReplicates = true;

	Mesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mesh"));
	// The view model must never collide or cast into the world — it lives in front of the camera.
	Mesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	Mesh->SetCastShadow(false);
	RootComponent = Mesh;
}

void APhotonWeapon::InitialiseFromData(const UPhotonWeaponData* InData)
{
	Data = InData;
	if (!Data)
	{
		return;
	}
	if (Data->Mesh)
	{
		Mesh->SetStaticMesh(Data->Mesh);
	}
	// The first-person pose is authored per weapon in the data asset, so a longer or shorter weapon
	// sits correctly without code changes.
	Mesh->SetRelativeTransform(Data->HipTransform);
}

FVector APhotonWeapon::GetMuzzleWorld() const
{
	if (Mesh && Mesh->DoesSocketExist(TEXT("SOCKET_muzzle")))
	{
		return Mesh->GetSocketLocation(TEXT("SOCKET_muzzle"));
	}
	return Mesh ? Mesh->GetComponentTransform().TransformPosition(MuzzleOffset) : GetActorLocation();
}

float APhotonWeapon::GetCooldownRemaining() const
{
	if (!Data || !GetWorld())
	{
		return 0.f;
	}
	const float Elapsed = GetWorld()->GetTimeSeconds() - LastFireTime;
	return FMath::Max(0.f, Data->FireInterval - Elapsed);
}

bool APhotonWeapon::TryFire(APhotonCharacter* Shooter)
{
	if (!Data || !Shooter || !GetWorld())
	{
		return false;
	}
	// Fire rate is the weapon's business, not the character's. Refusing here means every path that can
	// request a shot — player input, a bot, a scripted test — is rate-limited identically.
	if (GetCooldownRemaining() > 0.f)
	{
		return false;
	}
	LastFireTime = GetWorld()->GetTimeSeconds();

	// The data assets generated by the bootstrap leave ProjectileClass unset, which made the weapon
	// count shots while spawning nothing — the self-test caught it as 0 bolts owned despite every fire
	// call being accepted. A per-weapon override still wins; this is only the floor.
	UClass* BoltClass = Data->ProjectileClass ? Data->ProjectileClass.Get() : APhotonProjectile::StaticClass();

	FVector Origin = GetMuzzleWorld();
	FRotator Aim = Shooter->GetControlRotation();
	if (const APlayerController* PC = Cast<APlayerController>(Shooter->GetController()))
	{
		FVector EyeLoc; FRotator EyeRot;
		PC->GetPlayerViewPoint(EyeLoc, EyeRot);
		// Aim comes from the camera, not the muzzle: the projectile has to go where the crosshair is,
		// or the weapon's screen position silently becomes an aiming offset.
		Aim = EyeRot;
	}

	FActorSpawnParameters Params;
	Params.Owner = Shooter;
	Params.Instigator = Shooter;
	Params.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;

	APhotonProjectile* Bolt = GetWorld()->SpawnActor<APhotonProjectile>(
		BoltClass, Origin, Aim, Params);
	if (!Bolt)
	{
		return false;
	}

	EPhotonTeam Team = EPhotonTeam::None;
	if (const UPhotonHealthComponent* Health = Shooter->FindComponentByClass<UPhotonHealthComponent>())
	{
		Team = Health->Team;
	}
	Bolt->InitialiseFrom(Data, Team, Shooter->GetController());
	Bolt->SetActorEnableCollision(true);
	// The shooter must not be hit by their own muzzle-adjacent bolt. The ignore lives on the moving
	// primitive, not the actor — AActor has no MoveIgnoreActorAdd.
	if (UPrimitiveComponent* BoltRoot = Cast<UPrimitiveComponent>(Bolt->GetRootComponent()))
	{
		BoltRoot->IgnoreActorWhenMoving(Shooter, true);
	}

	++ShotsFired;
	UE_LOG(LogTemp, Display,
		TEXT("[Photon] PHOTONVERIFY fired weapon=%s shot=%d bolt=%s ownerOk=%d origin=%s"),
		*Data->WeaponId.ToString(), ShotsFired, *Bolt->GetName(),
		Bolt->GetOwner() == Shooter, *Origin.ToCompactString());
	return true;
}

// ---------------------------------------------------------------------------------------------
// UPhotonInventoryComponent
// ---------------------------------------------------------------------------------------------

UPhotonInventoryComponent::UPhotonInventoryComponent()
{
	PrimaryComponentTick.bCanEverTick = false;
	SetIsReplicatedByDefault(true);
}

void UPhotonInventoryComponent::BeginPlay()
{
	Super::BeginPlay();
	BuildLoadout();
}

void UPhotonInventoryComponent::BuildLoadout()
{
	if (Weapons.Num() > 0)
	{
		return; // already built
	}
	// Default loadout by path when nothing is configured, so a bare PhotonCharacter placed in a level
	// is still armed. PH-6 first: it is the balanced primary and the weapon the player should start on.
	if (Loadout.Num() == 0)
	{
		const TCHAR* Paths[] = {
			TEXT("/Game/Photon/Weapons/DA_PH6_PhotonRifle.DA_PH6_PhotonRifle"),
			TEXT("/Game/Photon/Weapons/DA_PH9_Swift.DA_PH9_Swift"),
		};
		for (const TCHAR* Path : Paths)
		{
			if (UPhotonWeaponData* D = LoadObject<UPhotonWeaponData>(nullptr, Path))
			{
				Loadout.Add(D);
			}
			else
			{
				UE_LOG(LogTemp, Error, TEXT("[Photon] missing weapon data: %s"), Path);
			}
		}
	}

	APhotonCharacter* Owner = Cast<APhotonCharacter>(GetOwner());
	if (!Owner || !Owner->WeaponRoot)
	{
		UE_LOG(LogTemp, Error, TEXT("[Photon] inventory owner is not a PhotonCharacter with a WeaponRoot"));
		return;
	}

	for (const TObjectPtr<UPhotonWeaponData>& D : Loadout)
	{
		if (!D)
		{
			continue;
		}
		FActorSpawnParameters Params;
		Params.Owner = Owner;
		Params.Instigator = Owner;
		APhotonWeapon* W = GetWorld()->SpawnActor<APhotonWeapon>(
			APhotonWeapon::StaticClass(), FTransform::Identity, Params);
		if (!W)
		{
			continue;
		}
		W->InitialiseFromData(D);
		// Attached to the camera-parented WeaponRoot, so the view model follows look rotation without
		// the world mesh being involved. This is what the reference build could not do with one camera.
		W->AttachToComponent(Owner->WeaponRoot, FAttachmentTransformRules::KeepRelativeTransform);
		W->SetActorHiddenInGame(true);
		Weapons.Add(W);
	}

	UE_LOG(LogTemp, Display, TEXT("[Photon] PHOTONVERIFY loadout weapons=%d of data=%d"),
		Weapons.Num(), Loadout.Num());

	if (Weapons.Num() > 0)
	{
		EquipIndex(0);
	}
}

bool UPhotonInventoryComponent::EquipIndex(int32 Index)
{
	if (!Weapons.IsValidIndex(Index) || !Weapons[Index])
	{
		UE_LOG(LogTemp, Warning, TEXT("[Photon] equip refused, invalid index %d of %d"), Index, Weapons.Num());
		return false;
	}
	if (ActiveIndex == Index)
	{
		return true;
	}
	ActiveIndex = Index;
	ApplyActiveVisibility();
	// Report the resulting state, not the request. Returning true from "I asked it to equip" is how a
	// switch that did nothing gets reported as working.
	const bool bOk = GetActiveWeapon() != nullptr && !GetActiveWeapon()->IsHidden();
	UE_LOG(LogTemp, Display, TEXT("[Photon] PHOTONVERIFY equip index=%d id=%s visible=%d"),
		ActiveIndex, *GetActiveWeaponId().ToString(), bOk);
	return bOk;
}

bool UPhotonInventoryComponent::EquipNext()
{
	if (Weapons.Num() == 0)
	{
		return false;
	}
	return EquipIndex((ActiveIndex + 1) % Weapons.Num());
}

void UPhotonInventoryComponent::ApplyActiveVisibility()
{
	for (int32 i = 0; i < Weapons.Num(); ++i)
	{
		if (Weapons[i])
		{
			Weapons[i]->SetActorHiddenInGame(i != ActiveIndex);
		}
	}
}

void UPhotonInventoryComponent::OnRep_ActiveIndex()
{
	ApplyActiveVisibility();
}

APhotonWeapon* UPhotonInventoryComponent::GetActiveWeapon() const
{
	return Weapons.IsValidIndex(ActiveIndex) ? Weapons[ActiveIndex].Get() : nullptr;
}

FName UPhotonInventoryComponent::GetActiveWeaponId() const
{
	const APhotonWeapon* W = GetActiveWeapon();
	return (W && W->Data) ? W->Data->WeaponId : NAME_None;
}

void UPhotonInventoryComponent::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);
	DOREPLIFETIME(UPhotonInventoryComponent, ActiveIndex);
}
